/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from '@solana/kit';

export type VaultInitialized = {
  owner: Address;
  amount: bigint;
  unlockTimestamp: bigint;
  mint: Option<Address>;
};

export type VaultInitializedArgs = {
  owner: Address;
  amount: number | bigint;
  unlockTimestamp: number | bigint;
  mint: OptionOrNullable<Address>;
};

export function getVaultInitializedEncoder(): Encoder<VaultInitializedArgs> {
  return getStructEncoder([
    ['owner', getAddressEncoder()],
    ['amount', getU64Encoder()],
    ['unlockTimestamp', getI64Encoder()],
    ['mint', getOptionEncoder(getAddressEncoder())],
  ]);
}

export function getVaultInitializedDecoder(): Decoder<VaultInitialized> {
  return getStructDecoder([
    ['owner', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['unlockTimestamp', getI64Decoder()],
    ['mint', getOptionDecoder(getAddressDecoder())],
  ]);
}

export function getVaultInitializedCodec(): Codec<
  VaultInitializedArgs,
  VaultInitialized
> {
  return combineCodec(
    getVaultInitializedEncoder(),
    getVaultInitializedDecoder()
  );
}
